#!/sbin/openrc-run
# Copyright 2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

description="Navidrome music server daemon"
command="/usr/bin/navidrome"
command_args="${NAVIDROME_OPTIONS}"
command_user="${NAVIDROME_USER}:${NAVIDROME_GROUP}"
directory="/var/lib/navidrome"
pidfile="/run/${RC_SVCNAME}.pid"
output_log="/var/log/navidrome.log"
error_log="/var/log/navidrome.log"

depend() {
	need net
}

start_pre() {
	checkpath -d -m 0750 -o "${command_user}" /var/lib/navidrome
	checkpath -f -m 0640 -o "${command_user}" /var/log/navidrome.log
}
