# Copyright 1999-2012 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $
# Ebuild generated by g-pypi 0.3

EAPI="4"
PYTHON_DEPEND="2:2.5"
SUPPORT_PYTHON_ABIS="1"
RESTRICT_PYTHON_ABIS="2.4 3.*"
DISTUTILS_SRC_TEST="setup.py"

inherit distutils


DESCRIPTION="browser abstraction for web acceptance testing"
HOMEPAGE="UNKNOWN"
SRC_URI="http://pypi.python.org/packages/source/s/splinter/${P}.tar.gz"

LICENSE=""
KEYWORDS="~amd64"
SLOT="0"
IUSE=""

DEPEND="dev-python/setuptools"
RDEPEND="!<dev-python/lxml-2.4.0
	>=dev-python/lxml-2.3.1
	>=dev-python/selenium-2.25.0
	dev-python/setuptools
	test? ( dev-python/coverage )
	test? ( dev-python/flask )"


