# Copyright 1999-2012 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $
# Ebuild generated by g-pypi 0.3

EAPI="6"

PYTHON_COMPAT=( python2_7 )
DISTUTILS_SRC_TEST="setup.py"

inherit distutils-r1


DESCRIPTION="Command line script to administer the Amazon Route 53 DNS service"
HOMEPAGE="http://loads.pickle.me.uk/cli53/"
SRC_URI="https://github.com/barnybug/cli53/archive/${PV}.tar.gz -> ${P}.tar.gz"

LICENSE="MIT"
KEYWORDS="~amd64"
SLOT="0"
IUSE=""

DEPEND="dev-python/setuptools"
RDEPEND="dev-python/argparse
	dev-python/boto
	dev-python/dnspython
	dev-python/setuptools"
