# Copyright 1999-2012 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $
# Ebuild generated by g-pypi 0.3

EAPI="4"
PYTHON_DEPEND="2:2.5"
SUPPORT_PYTHON_ABIS="1"
RESTRICT_PYTHON_ABIS="2.4 3.*"
DISTUTILS_SRC_TEST="setup.py"

inherit distutils


DESCRIPTION="Command line script to administer the Amazon Route 53 DNS service"
HOMEPAGE="http://loads.pickle.me.uk/cli53/"
SRC_URI="http://pypi.python.org/packages/source/c/cli53/${P}.tar.gz"

LICENSE="MIT"
KEYWORDS="~amd64"
SLOT="0"
IUSE=""

DEPEND="dev-python/setuptools"
RDEPEND="dev-python/argparse
	dev-python/boto
	dev-python/dnspython
	dev-python/setuptools"


