# Copyright 2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Autogenerated by pycargoebuild 0.15.1

EAPI=8
PYTHON_COMPAT=( python3_{11..14} )
DISTUTILS_USE_PEP517=maturin

CRATES="
	ahash@0.8.12
	anyhow@1.0.102
	atomic@0.6.1
	autocfg@1.5.0
	bitflags@2.11.1
	block-buffer@0.10.4
	bumpalo@3.20.2
	bytemuck@1.25.0
	cc@1.2.62
	cfg-if@1.0.4
	cfg_aliases@0.2.1
	chacha20@0.10.0
	cpufeatures@0.3.0
	crypto-common@0.1.7
	digest@0.10.7
	equivalent@1.0.2
	find-msvc-tools@0.1.9
	foldhash@0.1.5
	futures-core@0.3.32
	futures-task@0.3.32
	futures-util@0.3.32
	generic-array@0.14.7
	getrandom@0.3.4
	getrandom@0.4.2
	hashbrown@0.15.5
	hashbrown@0.17.1
	heck@0.5.0
	id-arena@2.3.0
	indexmap@2.14.0
	itoa@1.0.18
	js-sys@0.3.98
	leb128fmt@0.1.0
	libc@0.2.186
	log@0.4.29
	mac_address@1.1.8
	md-5@0.10.6
	memchr@2.8.0
	memoffset@0.9.1
	nix@0.29.0
	once_cell@1.21.4
	pin-project-lite@0.2.17
	portable-atomic@1.13.1
	prettyplease@0.2.37
	proc-macro2@1.0.106
	pyo3-build-config@0.28.3
	pyo3-ffi@0.28.3
	pyo3-macros-backend@0.28.3
	pyo3-macros@0.28.3
	pyo3@0.28.3
	python3-dll-a@0.2.15
	quote@1.0.45
	r-efi@5.3.0
	r-efi@6.0.0
	rand@0.10.1
	rand_core@0.10.1
	rustversion@1.0.22
	semver@1.0.28
	serde@1.0.228
	serde_core@1.0.228
	serde_derive@1.0.228
	serde_json@1.0.149
	sha1_smol@1.0.1
	shlex@1.3.0
	slab@0.4.12
	syn@2.0.117
	target-lexicon@0.13.5
	typenum@1.20.0
	unicode-ident@1.0.24
	unicode-xid@0.2.6
	uuid@1.23.1
	version_check@0.9.5
	wasip2@1.0.3+wasi-0.2.9
	wasip3@0.4.0+wasi-0.3.0-rc-2026-01-06
	wasm-bindgen-macro-support@0.2.121
	wasm-bindgen-macro@0.2.121
	wasm-bindgen-shared@0.2.121
	wasm-bindgen@0.2.121
	wasm-encoder@0.244.0
	wasm-metadata@0.244.0
	wasmparser@0.244.0
	winapi-i686-pc-windows-gnu@0.4.0
	winapi-x86_64-pc-windows-gnu@0.4.0
	winapi@0.3.9
	wit-bindgen-core@0.51.0
	wit-bindgen-rust-macro@0.51.0
	wit-bindgen-rust@0.51.0
	wit-bindgen@0.51.0
	wit-bindgen@0.57.1
	wit-component@0.244.0
	wit-parser@0.244.0
	zerocopy-derive@0.8.48
	zerocopy@0.8.48
	zmij@1.0.21
"

inherit cargo distutils-r1 pypi
src_prepare() {
	distutils-r1_src_prepare
	echo "[build-system]" >> pyproject.toml
	echo "requires = [\"maturin>=1.5,<2.0\"]" >> pyproject.toml
	echo "build-backend = \"maturin\" " >> pyproject.toml
}


DESCRIPTION=""
HOMEPAGE=""
SRC_URI="
	${CARGO_CRATE_URIS}
"

LICENSE=""
# Dependent crate licenses
LICENSE+=" Apache-2.0-with-LLVM-exceptions BSD MIT Unicode-3.0 ZLIB"
SLOT="0"
KEYWORDS="~amd64"
S="${WORKDIR}/${P}"
