# Copyright 1999-2012 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $
# Ebuild generated by g-pypi 0.2.2 (rev. 214)

EAPI=4

PYTHON_MODNAME="producteev"

inherit distutils


DESCRIPTION="Producteev API."
HOMEPAGE="https://github.com/magarcia/python-producteev"
SRC_URI="http://pypi.python.org/packages/source/p/producteev/${P}.tar.gz"
LICENSE="MIT"
KEYWORDS="~amd64"
SLOT="0"
IUSE=""
DEPEND="dev-python/setuptools"

