# specify on which port to listen
PORT=3333

# specify on which interface to listen, comment out to listen on all interfaces
HOST=127.0.0.1

# paths for config and metadata
CONFIG_PATH=/var/lib/audiobookshelf/config
METADATA_PATH=/var/lib/audiobookshelf/metadata
